# $FreeBSD$

PORTNAME=	lumina-themes
PORTVERSION=	201909070629
CATEGORIES=	x11-themes

MAINTAINER=	jt@ixsystems.com
COMMENT=	Lumina desktop wallpapers/colors

LICENSE=	CC0-1.0

USES=	qt:5 qmake
USE_QT=	qmake_build

USE_GITHUB=	yes
GH_ACCOUNT=	trueos
GH_PROJECT=	lumina-themes
GH_TAGNAME=	ebbbbb465359e1fb4c77f0811601f491f02f4649

.include <bsd.port.mk>
